ringcentral/ringcentral-embeddable

- src/adapter.js
- src/modules/Adapter/index.js
- src/modules/Interaction/index.js
> popup window when there is a incoming call

- src/index.html
> fix bugs on Edge and Safari

- README.md
- src/modules/Adapter/index.js
- src/modules/Interaction/index.js
- src/modules/Phone/index.js
add call control api #35 
add outbound call event #32
> add call control api and outbound call event to widget

- package.json
- src/components/Environment/index.js
- src/containers/AlertContainer/index.js
- src/containers/App/index.js
- src/containers/AppView/index.js
- src/containers/AppView/styles.scss
- src/containers/MainView/index.js
- src/modules/Adapter/styles.scss
- src/modules/Interaction/index.js
- src/modules/Phone/index.js
- src/modules/Phone/new.js
- webpack-dev-server.config.js
- webpack-production.config.js
- yarn.lock
upgrade ringcentral-widgets
add contacts page
> add contacts page

- src/components/AlertRenderer/index.js
- src/modules/ImplicitOAuth/authErrors.js
- src/modules/ImplicitOAuth/index.js
> checkout grant type and give explicit error

- src/containers/App/index.js
For #51 
New contact feature isn't implemented. So hide it
> Hide new contact button

- src/adapter.js
- src/index.html
- src/lib/Adapter/index.js
- src/lib/notification.js
> add desktop notification for ringing call on Adapter

- README.md
- docs/widget-event.md
- src/lib/Adapter/index.js
- src/modules/Adapter/index.js
- src/modules/MessageStore/index.js
> add message event

- README.md
- docs/README.md
- docs/third-party-service-in-widget.md
- src/components/LogIcon/index.js
- src/containers/App/index.js
- src/containers/CallsListPage/index.js
- src/containers/SettingsPage/index.js
- src/modules/CallLogger/index.js
- src/modules/Phone/index.js
- src/modules/ThirdPartyService/actionTypes.js
- src/modules/ThirdPartyService/getReducer.js
- src/modules/ThirdPartyService/index.js
As mentioned in #119 , this add feature to allow third party to add log button in calls page
> Support to log call to third party service

- README.md
- docs/README.md
- docs/third-party-service-in-widget.md
- src/components/AuthorizeSettingsSection/index.js
- src/components/AuthorizeSettingsSection/styles.scss
- src/containers/SettingsPage/index.js
- src/modules/Phone/index.js
- src/modules/ThirdPartyService/actionTypes.js
- src/modules/ThirdPartyService/getReducer.js
- src/modules/ThirdPartyService/index.js
> Support to register third party service authorization button

- src/modules/Contacts/index.js
- src/modules/Phone/index.js
> fix third party contact search bug

- docs/third-party-service-in-widget.md
- src/components/LogSectionModal/index.js
- src/components/LogSectionModal/styles.scss
- src/containers/App/index.js
- src/containers/CallLogSectionModal/index.js
- src/containers/CallsListPage/index.js
- src/modules/CallLogSection/index.js
- src/modules/CallLogger/index.js
- src/modules/Phone/index.js
- src/modules/ThirdPartyService/getReducer.js
- src/modules/ThirdPartyService/index.js
>  feat: support to show log modal when click log button

- docs/third-party-service-in-widget.md
- src/modules/ThirdPartyService/actionTypes.js
- src/modules/ThirdPartyService/getReducer.js
- src/modules/ThirdPartyService/index.js
> feat: support to only sync updated contacts

- src/lib/RedirectController.js
window will be closed after proxy removes stroage item.
> remove unused codes

- package.json
- src/modules/Phone/index.js
- yarn.lock
New features:
Upgrade ringcentral-web-phone to 0.6.3 (enable QOS in chrome)
Use Directory contacts api to instead account extension api and account phone number api.
Add presence dropdown select in floating window presence header in adapter mode.
> upgrade widgets to 0.10.2

- docs/third-party-service-in-widget.md
- src/components/AuthorizeSettingsSection/index.js
- src/components/AuthorizeSettingsSection/styles.scss
- src/components/ThirdPartyContactSourceIcon/index.js
- src/components/ThirdPartyContactSourceIcon/styles.scss
- src/containers/App/index.js
- src/containers/RecentActivityContainer/index.js
- src/containers/SettingsPage/index.js
- src/modules/ThirdPartyService/getReducer.js
- src/modules/ThirdPartyService/index.js
- test/steps/LoginWindow.js
> feat: support to set third party brand icon in authorization and contacts section

- package.json
- src/modules/Adapter/actionTypes.js
- src/modules/Adapter/index.js
- src/modules/Phone/index.js
- src/modules/ThirdPartyService/actionTypes.js
- yarn.lock
Use presence to replace detailedPresence
Use companyContacts to replace accountDirectory
Update moduleActionTypes import
> upgrage: widgets 0.10.6

- package.json
- src/containers/AppView/index.js
- src/containers/ThirdPartyConferenceInviteButton/index.js
- src/lib/Adapter/index.js
- src/lib/formatMeetingInfo/index.js
- src/modules/Phone/index.js
- yarn.lock
Webphone sdk 0.7.0
Webphone unavailable mode
Support to change inbound call to conference call
Support to call with format `mainNumber * extensionNumber`
> upgrade: widgets 0.10.7

- docs/interact-with-calling-settings.md
- src/adapter.js
- src/app.js
- src/lib/Adapter/index.js
- src/modules/Adapter/index.js
- src/modules/Phone/index.js
> feat: add from number in calling setting api

- README.md
- docs/README.md
- docs/multiple-tabs.md
- package.json
- src/adapter.js
- src/app.js
- src/index.html
- src/modules/Phone/index.js
- src/modules/Webphone/index.js
- yarn.lock
feat: support to disconnect inactive web phone instance
fix: web phone refresh page issue #270
> feat: support to disconnect inactive web phone instance

- src/modules/ConversationLogger/index.js
To date format error reported by https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/157
> fix: date format error in conversation logger

- package.json
- src/containers/App/index.js
- src/modules/OAuth/index.js
- src/modules/ThirdPartyService/index.js
- yarn.lock
upgrade: widgets [0.10.14](https://github.com/ringcentral/ringcentral-js-widgets/releases/tag/0.10.14)
enhance add type(manual) when user click contact refresh button
handle new oauth error
> upgrade: widgets 0.10.14

- docs/third-party-service-in-widget.md
- package.json
- src/containers/AppView/styles.scss
- yarn.lock
For #288 , show company and job title in contact detail page
> upgrade: widgets 0.10.15

- docs/widget-event.md
- src/lib/Adapter/index.js
- src/modules/Adapter/index.js
> feat: add region settings changed event

- package.json
- src/components/MeetingScheduleButton/index.js
- src/containers/App/index.js
- src/containers/ThirdPartyMeetingScheduleButton/index.js
- src/modules/OAuth/index.js
- src/modules/Phone/index.js
- yarn.lock
Add call switch feature #306 
Disable search popup when click on dial pad #287 
support to delete fax #289
> upgrade: use widgets 0.10.17

- README.md
- docs/config-client-id-and-secret.md
> docs: add document about how to graduate RC app from sandbox

- src/components/MeetingInviteModal/index.js
- src/components/MeetingInviteModal/styles.scss
- src/containers/App/index.js
- src/containers/MainView/index.js
- src/containers/MeetingInviteModal/index.js
- src/containers/ThirdPartyMeetingScheduleButton/index.js
- src/modules/MeetingInviteModalUI/actionTypes.js
- src/modules/MeetingInviteModalUI/getReducer.js
- src/modules/MeetingInviteModalUI/index.js
- src/modules/Phone/index.js
show meeting panel if user has permission, support copy to clipboard with scheduled meeting info
> feat: show meeting panel if user has permission, support copy to clipboard

- src/lib/Adapter/index.js
- src/modules/Adapter/index.js
> fix: wrong active call nocall event

- docs/control-widget.md
- src/modules/Adapter/index.js
> feat: add api to hold/unhold/tranfer/forward web phone call

- docs/third-party-service-in-widget.md
- src/lib/Adapter/index.js
- src/modules/Adapter/index.js
> feat: auto call logger changed event

- docs/control-widget.md
- docs/widget-event.md
- src/lib/Adapter/index.js
- src/modules/Adapter/index.js
> feat: support to record/mute web phone call by api and mute event

- docs/widget-event.md
- src/lib/Adapter/index.js
- src/modules/Adapter/index.js
> feat: show login number in rc-login-status-notify

- .gitignore
- README.md
- package.json
- src/adapter.js
- webpack-dev-server.config.js
- webpack-production.config.js
* Support to build for local browser extension files
* Redirect default to `${HOSTING_URL}/redirect.html`
> chore: update production build config

- src/internal-features/modules/MeetingProvider/index.js
- src/internal-features/modules/RcVideo/RcVideo.ts
- src/modules/RolesAndPermissions/index.js
> fix: init RCVideo with permission check

- README.md
- docs/README.md
- docs/third-party-service-in-widget.md
> docs: update rcv related docs

- src/modules/Phone/index.js
For https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/192 https://github.com/ringcentral/ringcentral-embeddable/issues/50
> feat: support to show mms image

- docs/control-widget.md
- src/modules/Adapter/index.js
> feat: add auto populate conversation text api

- package.json
- src/internal-features/components/GenericMeetingPanel/GenericMeetingPanel.tsx
- src/internal-features/containers/MeetingTabContainer/index.tsx
- src/modules/Phone/index.js
- test/steps/IframeWidget.js
- yarn.lock
Support to use CallerId from service web as default caller Id
> upgrade: widgets lib 0.11.1

- src/modules/CallLogger/index.js
- src/modules/GenericMeeting/index.ts
- src/modules/RcVideo/index.ts
enhance: allow to set default auto log initial status by storage
fix: rcv error
> enhance: allow to set default auto log initial status by storage

- package.json
- src/containers/App/index.js
- src/modules/Phone/index.js
> feat: support to send MMS

- docs/control-widget.md
- src/lib/Adapter/index.js
- src/modules/Adapter/index.js
for https://github.com/ringcentral/ringcentral-embeddable/issues/254
> feat(c2sms): go to conversation directly when conversation existed

- docs/widget-event.md
- src/modules/ActiveCallControl/index.js
- src/modules/Adapter/index.js
> feat: add telephony session event

- docs/customize-authorization.md
- docs/widget-event.md
- src/adapter.js
- src/app.js
- src/modules/OAuth/index.js
- src/modules/Phone/index.js
> feat: support to get oauth uri when click login button

- docs/control-widget.md
- src/modules/Adapter/index.js
- src/modules/OAuth/index.js
> feat: api to trigger login button click

- src/lib/Adapter/index.js
> fix: add allow-downloads in iframe sandbox

- src/modules/Webphone/index.js
- test/steps/LoginWindow.js
> fix: current call audio issue after a ringing call forwarded

- src/modules/OAuth/index.js
> fix: do not set special brand id for rc brand in login uri

- README.md
- docs/get-started.md
- src/lib/Adapter/index.js
> fix: add autoplay in iframe allow for ringing audio play issue

- src/modules/CallHistory/index.js
- src/modules/Phone/index.js
Fix https://github.com/ringcentral/ringcentral-embeddable/issues/516
> fix: call log rate limit issue at multiple tabs

- docs/disable-features.md
- src/adapter.js
- src/app.js
- src/components/RingtoneSettingsPanel/Ringtone.tsx
- src/components/RingtoneSettingsPanel/index.tsx
- src/components/RingtoneSettingsPanel/styles.scss
- src/containers/App/index.js
- src/containers/RingtoneSettingsPage/index.js
- src/containers/SettingsPage/index.js
- src/index.html
- src/modules/Phone/index.js
- src/modules/RolesAndPermissions/index.js
> feat: support to set ringtone

- src/modules/Webphone/helper.js
- src/modules/Webphone/index.js
> fix: show call queue name at call

- src/modules/Phone/index.js
> enhancement: redirect to calls page when call started at other devices

- src/modules/Webphone/index.js
> fix: keep call when user cancel page reload at firefox

- .eslintrc
- getWebpackBaseConfig.js
- vendors/commons/lib/validateIsOffline.js
patch validateIsOffline.js to fix logout issue when get ERR_NETWORK_CHANGED error
> fix: logout when get ERR_NETWORK_CHANGED error

- src/modules/Adapter/index.js
For https://github.com/ringcentral/ringcentral-embeddable-electron-app/issues/22
> fix: call dialer status notify issue

- docs/control-widget.md
- docs/disable-features.md
- src/adapter.js
- src/lib/Adapter/index.js
- src/lib/Adapter/styles.scss
> feat: allow to disable minimize

- src/lib/Adapter/index.js
- src/modules/Adapter/index.js
> feat: add isWindowPoppedUp in RCAdapter

- src/modules/Adapter/index.js
> fix: missing login number issue at event

- yarn.lock
for https://github.com/ringcentral/ringcentral-web-phone/issues/339
> chore: upgrade web phone sdk 0.8.9

- docs/disable-features.md
Based on suggestion from @embbnux  in https://github.com/ringcentral/ringcentral-embeddable/issues/588
> Update docs on enabling glip

- src/modules/AppFeatures/index.js
> fix: do not request video configuration without Meetings permission

- docs/control-widget.md
- docs/widget-event.md
- src/modules/Adapter/index.js
> feat: support to set userStatus and dndStatus

- docs/control-widget.md
- docs/widget-event.md
- package.json
- src/lib/Adapter/index.js
- src/modules/Adapter/index.js
> feat: add web phone session sync event

- getWebpackBaseConfig.js
- vendors/commons/lib/Tabbie.js
patch Tabbie to fix app keep loading issue when close popup window
> fix: web phone keep loading when close popup window

- src/modules/AppFeatures/index.js
- src/modules/GlipPersons/index.js
- src/modules/Phone/index.js
> fix: wrong permission check of glip person

- src/modules/Phone/index.js
> chore: web phone log level to 1

- package.json
- src/modules/Adapter/index.js
User reports that call may lost audio occasionally with some headphones before setting audio device.
> enhancement: set sink id again before call

- src/modules/Webphone/index.js
> fix: keep ringing when receive call at poor network

- docs/adapter-init.md
- src/adapter.js
> feat: support to manual init rc adapter

- src/app.js
- src/lib/TabFreezePrevention.ts
- src/lib/isFirefox.js
- src/lib/lockRefresh.js
- src/modules/Phone/index.js
- src/modules/Subscription/index.js
> fix: disable locks request at Firefox

- yarn.lock
for https://github.com/ringcentral/ringcentral-embeddable-electron-app/issues/69 with web phone sdk upgrading
> upgrade: web phone sdk 0.8.13

- src/app.js
> chore: remove client id warning when developer build by self

- package.json
- src/modules/AddressBook/index.ts
- src/modules/Phone/index.js
> fix: address book loading issue at next page

- package.json
- src/modules/DynamicBrand/index.js
- src/modules/Phone/index.js
> fix: brand logo missing at new brand

- getBrandConfig/atos/index.js
- getBrandConfig/att/index.js
- getBrandConfig/avaya/index.js
- getBrandConfig/bt/index.js
- getBrandConfig/rainbow/index.js
- getBrandConfig/rc/index.js
- getBrandConfig/telus/index.js
remove RingCentral Phone from calling method, user should use RingCentral App instead of RingCentral Phone
> feat: remove RingCentral Phone from calling method

- package.json
- src/components/AudioSettingsPanel/AudioSettingsPanel.interface.ts
- src/components/AudioSettingsPanel/VolumeSlider.tsx
- src/components/AudioSettingsPanel/index.tsx
- src/components/BackHeaderView/index.tsx
- src/components/RingtoneSettingsPanel/Ringtone.tsx
- src/components/RingtoneSettingsPanel/index.tsx
- src/components/SettingsPanel/AdditionalSettings.jsx
- src/containers/App/index.js
- src/containers/AudioSettingsPage/index.ts
- src/modules/AudioSettings/index.ts
- src/modules/AudioSettingsUI/index.ts
- src/modules/CallLogger/index.ts
- src/modules/Phone/index.js
- src/modules/RingtoneSettingsUI/index.ts
- src/modules/SettingsUI/index.js
- src/modules/Webphone/index.ts
- src/modules/Webphone/patchAudioHelper.ts
- test/steps/IframeWidget.js
- test/widget.test.js
- yarn.lock
* support to set ringtone device/volume
* support to set call volume
* move noise reduction setting to audio setting page
* move ringtone setting to audio setting page
> feat: new audio settings

- src/lib/Adapter/index.js
- src/modules/Adapter/index.js
> feat: api to set ringtone
